### ISSUE TITLE
missing dependency: forever-monitor

### ISSUE THREAD

**Issue by streaps** [garbados/quilter#13]
```
$ quilt -h

module.js:340
    throw err;
    ^
Error: Cannot find module 'forever-monitor'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oli/local/node_modules/quilter/bin/quilt.js:7:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by garbados** [comment]
Whoops. Will fix.

**Comment by garbados** [comment]
Fixed by commit e19926042611dc2b0d2e149378ad9c502af637bb

**Comment by garbados** [comment]
By the way, thanks for reporting this issue!

**Comment by streaps** [comment]
thanks for fixing it :)
