### ISSUE TITLE
Error: server_admin access is required for this request

### ISSUE THREAD

**Issue by daveeel** [garbados/quilter#22]
I followed the instruction. Tried as normal user and root. Also tried use admin account on remote cloudant. Remote DB is fine by curl testing.

What does the error mean and how to resolve it?

```
Error: server_admin access is required for this request
    at Request._callback (/usr/local/lib/node_modules/quilter/node_modules/nano/nano.js:307:39)
    at Request.self.callback (/usr/local/lib/node_modules/quilter/node_modules/nano/node_modules/request/request.js:129:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/quilter/node_modules/nano/node_modules/request/request.js:873:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/quilter/node_modules/nano/node_modules/request/request.js:824:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

**Comment by garbados** [comment]
Are you using Cloudant? Their interface may have changed recently, causing Quilt to break. I'll take a look and see.

**Comment by daveeel** [comment]
Yes, used Cloudant. Thanks in advance.
